### ISSUE TITLE
USER STORY : register an account

### ISSUE THREAD

**Issue by Mahsak89** [Mahsak89/probiz#1]
As a **Site User** I can **register an account** so that **Have a personal account and be able to see my profile**

 # Acceptance Criteria
* there should be a form for user to fill in
* there should be a username, first and last name, username,email, password, and password confirmation fields
* the submit button should be at the bottom of the form
* there should be a signin option for users who already have an account

# Tasks
- [x] Update the view: the form (HTML and CSS) should be available in the navbar  
- [x] added html page
- [x] adde urls to urls.py
- [x] test the functionality

**Comment by Mahsak89** [comment]
it is completed
