### ISSUE TITLE
USER STORY : access my user profile

### ISSUE THREAD

**Issue by Mahsak89** [Mahsak89/probiz#11]
As a **Site User** I can **access my user profile** so that ** i can see, edit and delete my appointment**
# Acceptance Criteria
* users can see  their account information
* users can edit and delete  their appointment by a button

#Tasks
- [x] Update the view:  (HTML and CSS) to include the userpanel
- [x] added html page
- [x] adde urls to urls.py
- [x] test the functionality

**Comment by Mahsak89** [comment]
it is completed
