### ISSUE TITLE
USER STORY : sign in/out feature

### ISSUE THREAD

**Issue by Mahsak89** [Mahsak89/probiz#2]
As a **Site User** I can **signin or signout to my   account** so that **I can book an appointment and Access my personal info**

 # Acceptance Criteria
* there should be a form for user to fill in to login
* there should be a username and password fields in my login page
* the submit button should be at the bottom of the form
* there should be a signup option for users who  doesn't already have an account
* after sign in there should be a success massage
* if  the password or username filled wrong there should be amasssage
* after sign out there should be a massage

# Tasks
- [x] Update the view: the form (HTML and CSS) should be available in the navbar  
- [x] added html page
- [x] adde urls to urls.py
- [x] test the functionality

**Comment by Mahsak89** [comment]
finished all tasks

**Comment by Mahsak89** [comment]
it is completed
