### ISSUE TITLE
USER STORY : booking a service for consulting

### ISSUE THREAD

**Issue by Mahsak89** [Mahsak89/probiz#4]
As a **Site User** I can **book an appointment** so that **I can receive professional advice for my business**

 # Acceptance Criteria
* there should be a form in which users can choose their needed service and choose between the available dates and times

# Tasks
- [x] Update the view: the form (HTML and CSS) should be available in the navbar and header 
- [x] added an appointment model
- [x] added html page
- [x] adde urls to urls.py
- [x] test the functionality

**Comment by Mahsak89** [comment]
it is completed
